version: '3.8'
services:
  prometheus:
    image: prom/prometheus
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    network_mode: "host"
  grafana:
    image: grafana/grafana
    volumes:
    - grafana_volume
    network_mode: "host"
  influxdb:
    image: influxdb
    volumes:
    - ./influxdb.conf:/etc/influxdb/influxdb.conf
    network_mode: "host"